spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emp

  jpa:
    hibernate:
      ddl-auto: no

  liquibase:
    enabled: false #Doesn't update liquibase while app running